### ISSUE TITLE
How to create icons

### ISSUE THREAD

**Issue by kootenpv** [digitalcraftsman/hugo-artists-theme#12]
It would be great if there is a section (or a link to somewhere) explaining how we could reproduce the existing icons, and how to create new icons ourselves. Thanks for the awesome theme!

**Comment by digitalcraftsman** [comment]
Hello @kootenpv,

this theme is a port of the original theme and I just took the assets, including this icons, as they are. I'm not a graphical designer or anything alike. Hence I can't really help you in this department. 

But you might find some pointers in the [original PSD file](https://github.com/DevTips/Artists-Theme/blob/gh-pages/the_design.psd) of the theme or the [video series](https://www.youtube.com/watch?v=T6jKLsxbFg4&list=PLqGj3iMvMa4KQZUkRjfwMmTq_f1fbxerI) that documented the whole design and developement process of the original Jekyll theme.

**Comment by kootenpv** [comment]
Thanks, it was my bad for realizing it is not the right place to ask. Though you really helped! I found a URL in one of the vids: https://icomoon.io/#preview-free

**Comment by digitalcraftsman** [comment]
Great!
