### ISSUE TITLE
is it possible to create separated "work" sections?

### ISSUE THREAD

**Issue by shaief** [digitalcraftsman/hugo-artists-theme#5]
i would like to create separated work sections - each for different category. Can it be done easily?

Thanks!

**Comment by digitalcraftsman** [comment]
I tried it by changing the template logic and the settings in the console, but I see the main problem in Javascript part. I'm not familiar with the (JS) codebase itself nor I'm an expert in JS itself.

**Comment by shaief** [comment]
@digitalcraftsman thanks!
