### ISSUE TITLE
Adding contact icon

### ISSUE THREAD

**Issue by Rovanion** [digitalcraftsman/hugo-artists-theme#9]
Hi, this might be a stupid question but: How can I add a contact icon to the theme?

I understand that the icons are added through some sort of font trickery but I can't find the file which dictates what these glyphs look like. Can you point me in the right direction?

**Comment by digitalcraftsman** [comment]
Hello @Rovanion,

you mean the icons in the contact section, right? Travis (aka DevTips), the original theme creator, used an online tool called [icomoon](https://icomoon.io/) to generate a custom font based on popular icon sets.

However, we made a whole series of how he created this theme including the generation of a custom icon set. Watch [this video](https://www.youtube.com/watch?v=YC6PSSCIVjQ&index=22&list=PL0CB3OvPhDA_STygmp3sDenx3UpdOMk7P) and follow the instructions.

In the next step you need to add the base64-encoded font [here](https://github.com/digitalcraftsman/hugo-artists-theme/blob/master/static/css/all.css#L443).

I hope this helps.

**Comment by Rovanion** [comment]
Yes, that's the icons I'm looking at changing!

So the font was inlined in the CSS? Well that explains why I couldn't find any trace of the font file in the source code or when the page was loaded.

Thank you for your kind help.
God Jul!

**Comment by digitalcraftsman** [comment]
> So the font was inlined in the CSS?

The base64-conded font was embedded in the codeline that I linked above. 

Do you've other questions or can this issue be closed?

**Comment by Rovanion** [comment]
Oh yeah sorry, I should have closed it already. Thank you once again.
